name: taskmate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:
  flame: ^1.30.1
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

  
  table_calendar: ^3.0.0
  pie_chart: ^5.4.0
  path_provider: ^2.0.11
  vector_math: ^2.1.4
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_auth: ^6.0.1
  http: ^1.1.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.5.0  
  timezone: ^0.10.0  
  web: ^1.1.1
  js: ^0.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/bgm1.mp3
    - assets/sounds/bgm2.wav
  
  uses-material-design: true
